DEVICE: cuda
SAVE_DIR: 'output'

DATASET:
  ROOT: ''

MODEL:
  NAME: CSWin
  VARIANT: B
  PRETRAINED: 'C:/_workspace/k_HappyWhale/models/cswin_base_224.pth'
  FREEZE: false

TRAIN:
  IMAGE_SIZE: [448, 448]
  EPOCHS: 100
  BATCH_SIZE: 8
  EVAL_INTERVAL: 20
  AMP: true
  DDP: false

EVAL:
  IMAGE_SIZE: [448, 448]
  BATCH_SIZE: 8
  MODEL_PATH: 'output/cswin_base_224.pth'

OPTIMIZER:
  NAME: adamw
  LR: 0.0005
  DECAY: 0.05

SCHEDULER:
  NAME: steplr
  STEP_SIZE: 30
  GAMMA: 0.1