DEVICE: cuda
SAVE_DIR: 'output'

DATASET:
  ROOT: ''

MODEL:
  NAME: CSWin
  VARIANT: B

KD:
  ENABLE: false
  ALPHA: 0.9
  TEMP: 10
  TEACHER:
    NAME: CSWin
    VARIANT: B
    PRETRAINED: 'C:/_workspace/k_HappyWhale/models/cswin_base_224.pth'

TRAIN:
  IMAGE_SIZE: [672, 672]
  EPOCHS: 300
  BATCH_SIZE: 2
  EVAL_INTERVAL: 20
  AMP: true
  DDP: false

EVAL:
  IMAGE_SIZE: [672, 672]
  BATCH_SIZE: 2
  MODEL_PATH: 'output/CSWin_672_base.pth'

OPTIMIZER:
  NAME: adamw
  LR: 0.0005
  DECAY: 0.05

SCHEDULER:
  NAME: steplr
  STEP_SIZE: 30
  GAMMA: 0.1